### ISSUE TITLE
Dsp.h generation

### ISSUE THREAD

**Issue by gorborukov** [miccio-dk/LeslieSim#1]
How did you generate the [Dsp.h](https://github.com/miccio-dk/LeslieSim/blob/master/juce/LeslieSim/Source/Dsp.h) file? Did you create it manually? It looks like DspFaust.cpp, but cleared of unnecessary code.

**Comment by miccio-dk** [comment]
Hey! It's been automatically generated using a custom template which is based on the one mentioned in [this old FAUST tutorial]( https://ccrma.stanford.edu/courses/256a-fall-2016/lectures/faust/). 
Depending on whether [this bug](https://github.com/grame-cncm/faust/issues/273) has been fixed on upstream FAUST, this might not be needed and the whole app could be ported to work with the most recent practices, as explained [here](https://faustdoc.grame.fr/workshops/2020-04-10-faust-juce/#simple-audio-effect-plug-in).

**Comment by gorborukov** [comment]
> Hey! It's been automatically generated using a custom template which is based on the one mentioned in [this old FAUST tutorial](https://ccrma.stanford.edu/courses/256a-fall-2016/lectures/faust/).
> Depending on whether [this bug](https://github.com/grame-cncm/faust/issues/273) has been fixed on upstream FAUST, this might not be needed and the whole app could be ported to work with the most recent practices, as explained [here](https://faustdoc.grame.fr/workshops/2020-04-10-faust-juce/#simple-audio-effect-plug-in).

Thanks for the detailed answer!
